### ISSUE TITLE
4. Arquitectura General(Diagrama)

### ISSUE THREAD

**Issue by LizVasquez** [LL2N/LL2N#18]
**COMO LL2N**
**QUEREMOS** realizar el diagrama general para el proyecto
**PARA** dar a conocer la arquitectura de software que utilizaremos

**Comment by nuriamichel** [comment]
Ya determinada la arquitectura buscamos un poco de información para poder realizar el diagrama

**Comment by LizVasquez** [comment]
La arquitectura general ya fue introducida en la sección de arquitectura de software en wiki.
