### ISSUE TITLE
5. Sprint tareas completadas

### ISSUE THREAD

**Issue by luvellana** [LL2N/LL2N#19]
**COMO LL2N**
**QUEREMOS** realizar una tabla de las tareas completadas
**PARA** tener una mejor organización en el proyecto

**Comment by LizVasquez** [comment]
Hacer la tabla de tareas completadas en wiki con sus estimaciones y estado.

**Comment by LizVasquez** [comment]
La tabla ya se encuenta en la sección de Scrum en Wiki.
