### ISSUE TITLE
4. Arqui front-end (Diagrama)

### ISSUE THREAD

**Issue by LizVasquez** [LL2N/LL2N#20]
**Como LL2N**
**QUEREMOS** realizar un diagrama de arquitectura 
**PARA** tener una idea clara del funcionamiento del front-end

**Comment by nuriamichel** [comment]
Se agregó un fondo celeste al diagrama

**Comment by nuriamichel** [comment]
Finalizado y ya se encuentra en la sección del wiki correspondiente
