### ISSUE TITLE
5. Sprint tareas arrastradas

### ISSUE THREAD

**Issue by luvellana** [LL2N/LL2N#21]
**COMO LL2N**
**QUEREMOS** realizar una tabla de las tareas arrastradas
**PARA**  no olvidar algo pendiente

**Comment by LizVasquez** [comment]
Añadir la tabla de tareas arrastradas a wiki con estimaciones y estado.

**Comment by LizVasquez** [comment]
La tabla ya se encuentra en la sección de Scrum en wiki.
