### ISSUE TITLE
4. Arquitectura de Back-End: Diagrama

### ISSUE THREAD

**Issue by nuriamichel** [LL2N/LL2N#23]
**Como LL2N**
**QUEREMOS** realizar un diagrama de arquitectura
**PARA** tener una idea clara del funcionamiento del back-end

**Comment by LizVasquez** [comment]
Empezar con el diagrama en drive y pensar en las tecnologías que usaremos.

**Comment by luvellana** [comment]
diagrama finalizado, ya se encuentra en wiki
