### ISSUE TITLE
4. Arquitectura de Back-End: Tecnologías

### ISSUE THREAD

**Issue by nuriamichel** [LL2N/LL2N#24]
**Como LL2N**
**QUEREMOS** listar las tecnologías que vamos a utilizar
**PARA** tener una idea clara del desarrollo del back-end

**Comment by nuriamichel** [comment]
Se realizo un listado de las tecnologías que vamos a utilizar en el back-end

**Comment by luvellana** [comment]
resultado disponibles en wiki seccion 4
