### ISSUE TITLE
2. Casos de Usuario Regular: Noticias y Comunicados 

### ISSUE THREAD

**Issue by nuriamichel** [LL2N/LL2N#27]
COMO LL2N
QUEREMOS realizar el caso de uso de un usuario regular de Noticias y Comunicados
PARA poder mostrar el flujo que seguirá este usuario

**Comment by nuriamichel** [comment]
Se corrigió la parte de noticias a comunicados y noticias

**Comment by luvellana** [comment]
tarea finalizada, ya se encuentra en wiki
