### ISSUE TITLE
2. Casos de Usuario Regular: Rutas

### ISSUE THREAD

**Issue by nuriamichel** [LL2N/LL2N#28]
COMO LL2N
QUEREMOS hacer el diagrama de  usuario regular
PARA QUE  podamos entender mejor el proceso que se llevará a cabo por parte de este usuario

**Comment by nuriamichel** [comment]
Se añadieron las categorias de noticias y comunicado

**Comment by luvellana** [comment]
ruta definida, finalizado en wiki
