### ISSUE TITLE
2. Casos de Usuario Regular: Sobre La Paz Bus

### ISSUE THREAD

**Issue by nuriamichel** [LL2N/LL2N#29]
COMO LL2N
QUEREMOS realizar el caso de uso de un usuario regular
PARA QUE se entienda mejor el proceso

**Comment by nuriamichel** [comment]
Se realizaron pequeñas correcciones para esta parte en cuanto al flujo del usuario

**Comment by luvellana** [comment]
dicho flujo y diagrama se encuentra ya en wiki
