### ISSUE TITLE
2. Caso de uso - sobre La Paz Bus

### ISSUE THREAD

**Issue by LizVasquez** [LL2N/LL2N#32]
COMO LL2N
QUEREMOS hacer el caso de uso del usuario editor sobre La Paz Bus
PARA mostrar las acciones y el flujo que podrá seguir este tipo de usuario

**Comment by luvellana** [comment]
definir el contenido de esta sección para cada usuario

**Comment by luvellana** [comment]
finalizado y disponible en wiki
