### ISSUE TITLE
Arquitectura de Software

### ISSUE THREAD

**Issue by LizVasquez** [LL2N/LL2N#5]
**COMO** LL2N
**QUEREMOS** Tener la estructura del proyecto definido
**PARA** Un desarrollo optimo

**Comment by LizVasquez** [comment]
definir las tecnologías que usaremos para front end y back end

**Comment by LizVasquez** [comment]
Los diagramas de arquitectura de software ya se encuentran en Wiki.

**Comment by nuriamichel** [comment]
Finalizado , y ya se encuentra en la sección correspondiente del wiki
