### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by LizVasquez** [LL2N/LL2N#7]
**Como** LL2N 
**QUEREMOS** Tener una base de lo que se espera del proyecto
**PARA QUE** tengamos mejor definida la interfaz

**Comment by hrnn** [comment]
<img width="1465" alt="Screen Shot 2020-11-12 at 4 13 49 PM" src="https://user-images.githubusercontent.com/854676/99068744-76dbec80-2583-11eb-84e1-8e31fda4c71c.png">

**Comment by luvellana** [comment]
ya esta la base grafica
solo falta prototipar las distintas pantallas

**Comment by LizVasquez** [comment]
Los prototipos ya se realizaron e introducieron en la parte de Mockups en Wiki.
