### ISSUE TITLE
1.Objetivo del Proyecto

### ISSUE THREAD

**Issue by LizVasquez** [LL2N/LL2N#9]
**COMO LL2N**
**QUEREMOS** describir el objetivo del proyecto
**PARA** dar a conocer lo que haremos en el mismo

**Comment by nuriamichel** [comment]
Ya con la descripción del proyecto se pudo plantear un objetivo

**Comment by nuriamichel** [comment]
Finalizado, y ya se encuentra en la sección correspondiente del wiki
